api/urls.py
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views
from . import views

app_name = "api"
urlpatterns = [
    path("videogames", views.VideogamesView.as_view(), name="video_games"),
    path("videogame/<id>", views.VideogameView.as_view(), name="video_game"),
    path("user/<user_id>/videogames", views.UserVideogamesView.as_view(), name="video_games"),
    path("token/", jwt_views.TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", jwt_views.TokenRefreshView.as_view(), name="token_refresh"),
    path("api-auth/", include("rest_framework.urls")),
    path("logout/", views.LogoutView.as_view(), name="logout"),
]

jeux/urls.py
from django.urls import path
from django.conf.urls import handler400, handler403, handler404, handler500
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = "jeux"
urlpatterns = [
    path("", views.index, name="index"),
    path("loginside", views.loginside, name="loginside"),
    path("logoutside", views.logoutside, name="logoutside"),
    path("accueil", views.accueil, name="accueil"),
    path("config", views.config, name="config"),
    path("change_info", views.change_info, name="change_info"),
    path("mes_jeux", views.mes_jeux, name="mes_jeux"),
    path("mes_jeux_ajouter", views.mes_jeux_ajouter, name="mes_jeux_ajouter"),
    path("mes_jeux_enlever", views.mes_jeux_enlever, name="mes_jeux_enlever"),
    path("ajouter_jeu_bdd", views.ajouter_jeu_bdd, name="ajouter_jeu_bdd"),
    path("mes_amis", views.mes_amis, name="mes_amis"),
    path("ajax/vote_jeuvideo", views.ajax_vote_videogame, name="ajax_vote_videogame"),
    path("jeux_societe", views.jeux_societe, name="jeux_societe"),
    path(
        "ajouter_jeu_societe_bdd",
        views.ajouter_jeu_societe_bdd,
        name="ajouter_jeu_societe_bdd",
    ),
    path("reset_password", views.reset_password, name="reset_password"),
    path("reset_page", views.reset_page, name="reset_page"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    handler400 = "jeux.views.bad_request"
    handler403 = "jeux.views.permission_denied"
    handler404 = "jeux.views.page_not_found"
    handler500 = "jeux.views.server_error"

lanrumble/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.http import HttpResponse
import os
from dotenv import load_dotenv

load_dotenv()


urlpatterns = [
    path("", include("jeux.urls")),
    path("rectangle_game/", include("rectangle_game.urls")),
    path("chat/", include("chat.urls")),
    path("admin/", admin.site.urls),
    re_path(r"^robots.txt$", lambda r: HttpResponse("User-agent: *</br>Disallow: /")),
    path("api/", include("api.urls")),
]

if os.environ["DEBUG"]:
    from django.conf import settings
    from django.conf.urls.static import static

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jeux/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse    # QueryDict,
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout, password_validation
# from django.core.files.storage import FileSystemStorage
from django.utils.translation import gettext
from django.utils import timezone
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import login_required
from .models import Jeu, Joueur, Jeu_Societe, Vote_Jeu_Video, TokenResetPassword
from .forms import ConfigColorsForm, PasswordResetForm
from os import path, remove
from datetime import time, timedelta
import re, secrets


validate_mail_regexp = re.compile('^[0-9a-zA-Z.-_]{3,}@[0-9a-zA-Z-_]{2,}\.[a-zA-Z0-9]{2,}$')
log_dir = '/var/log/nginx/'
log_file = 'user_connections.log'


def joueur_colors(joueur_id):
    """Fonction pour avoir la liste des couleurs de l'utilisateur logé"""
    try:
        joueur = Joueur.objects.get(utilisateur=joueur_id)
    except Exception as e:
        print(e)
    return {
        'body_background': joueur.color_body_background,
        'body_text': joueur.color_body_text,
        'nav_background': joueur.color_nav_background,
        'nav_link_active': joueur.color_nav_link_active,
        'nav_link_hover': joueur.color_nav_link_hover,
        'nav_link': joueur.color_nav_link,
        'nav_text': joueur.color_nav_text
    }


def joueur_background(request):
    """Fonction pour avoir le fond d'écran de l'utilisateur logé"""
    try:
        background_image = Joueur.objects.get(
            utilisateur=request.user.id).background_file.url
    except Exception:
        background_image = ""
    return background_image


def gestionnaire_erreur(func):
    """Fonction qui gère les erreurs"""
    def inner(request, *args, **kwargs):
        if 'error_not_seen' in request.session and 'error_message' in request.session:
            if request.session['error_not_seen']:
                request.session['error_not_seen'] = False
            else:
                request.session['error_message'] = ''
        else:
            request.session['error_message'] = ''
            request.session['error_not_seen'] = False
        return func(request, *args, **kwargs)
    return inner


@gestionnaire_erreur
def index(request):
    if request.user.is_authenticated:
        return redirect('jeux:accueil')
    else:
        return render(request, 'jeux/index.html',
                      {'jeux': Jeu.objects.all()})


def loginside(request):
    """Vue de connection"""
    pseud = request.POST.get('pseudo')
    passwd = request.POST.get('password')
    user = authenticate(request, username=pseud, password=passwd)
    if user is not None:
        login(request, user)
    else:
        with open(path.join(log_dir, log_file), 'a') as log_file_opened:
            log_file_opened.write(request.META['HTTP_X_REAL_IP'] + ' - ' +
                                  timezone.now().strftime("%Y/%m/%d %H:%M:%S +%Z") + ' - ' + pseud + '\n')
        request.session['error_message'] += 'Login ou mot de passe incorrect.\\n'
        request.session['error_not_seen'] = True
        return redirect('jeux:index')
    try:
        joueur = Joueur.objects.get(utilisateur=user.id)
        joueur.utilisateur.check_password(passwd)
    except Exception:
        request.session['error_message'] += 'Utilisateur introuvable.\\n'
        request.session['error_not_seen'] = True
        return render(request, 'jeux/index.html',
                      {'jeux': Jeu.objects.all()})
    else:
        request.session['pseudo'] = joueur.utilisateur.username
        return redirect('jeux:accueil')


def logoutside(request):
    if request.user.is_authenticated:
        request.session.clear()
        logout(request)
    return redirect('jeux:index')


@login_required(login_url='/')
@gestionnaire_erreur
def accueil(request, error_message=False):
    try:
        joueur = Joueur.objects.get(utilisateur=request.user.id)
    except Exception:
        request.session['error_message'] += 'Utilisateur introuvable.\\n'
        request.session['error_not_seen'] = False
        return redirect('jeux:index')
    else:
        amis = {}
        liste_jeux = {}
        for ami in joueur.amis.all():
            amis[ami.utilisateur.username] = []
            for jeu in ami.liste_jeux.all():
                try:
                    vote = Vote_Jeu_Video.objects.filter(joueur_concerne=ami.id).filter(jeu_concerne=jeu.id).get().valeur
                except Exception:
                    vote = 5
                amis[ami.utilisateur.username].append([jeu.nom, vote])

        for jeu in joueur.liste_jeux.all():
            liste_jeux[jeu.nom] = {}
            liste_jeux[jeu.nom]['id'] = jeu.id
            liste_jeux[jeu.nom]['pvp'] = jeu.pvp
            liste_jeux[jeu.nom]['coop'] = jeu.coop
            liste_jeux[jeu.nom]['f2p'] = jeu.f2p
            liste_jeux[jeu.nom]['joueurs_online'] = jeu.joueurs_max_online
            liste_jeux[jeu.nom]['joueurs_hot_seat'] = jeu.joueurs_max_hot_seat
            try:
                liste_jeux[jeu.nom]['my_vote'] = Vote_Jeu_Video.objects.filter(joueur_concerne=joueur.id).filter(jeu_concerne=jeu.id).get().valeur
            except Exception:
                liste_jeux[jeu.nom]['my_vote'] = 5
        # TODO DOING: alerter l'user si il n'a pas mis son mail dans la bdd
        if (User.objects.get(username=joueur.utilisateur).email == ""):
            request.session['error_message'] += 'Veuillez remplir votre addresse mail dans Mon Compte.\\n'
            request.session['error_not_seen'] = False

        return render(request, 'jeux/accueil.html',
                      {'amis': amis, 'liste_jeux': liste_jeux,
                       'colors': joueur_colors(request.user.id), 'background_image': joueur_background(request)})


@login_required(login_url='/')
@gestionnaire_erreur
def config(request):
    form_colors = ConfigColorsForm(
        instance=Joueur.objects.get(utilisateur=request.user.id))
    password_validators = ''
    for p in password_validation.password_validators_help_texts():
        password_validators += gettext(p) + '\\n'
    return render(request, 'jeux/config.html',
                  {'colors': joueur_colors(request.user.id), 'form_colors': form_colors, 'background_image': joueur_background(request),
                   'password_validators': re.sub(r'\'', "\\'", password_validators)})



@gestionnaire_erreur
def change_info(request):
    if request.user.check_password(request.POST.get('password')) and request.method == 'POST':
        if request.POST.get('password_new_1') != request.POST.get('password_new_1'):
            request.session['error_message'] += "Les nouveaux mots de passe ne correspondent pas.\\n"
            request.session['error_not_seen'] = True
        elif not request.POST.get('password_new_1') == "" and password_validation.validate_password(request.POST.get('password')) is None:
            request.user.set_password(request.POST.get('password_new_1'))
            login(request, authenticate(
                request, username=request.user.username, password=request.POST.get('password')))
            request.user.save()
            request.session['error_message'] += "Mot de passe changé.\\n"
            request.session['error_not_seen'] = True
            print("Mot de passe changé pour " + request.user.username)
        elif request.POST.get('password_new_1') != "" and password_validation.validate_password(request.POST.get('password')) is not None:
            request.session['error_message'] += "Nouveau mot de passe incorrect.\\n"
            request.session['error_not_seen'] = True
        if validate_mail_regexp.match(request.POST.get('email')) and request.POST.get('email') != request.user.email:
            request.user.email = request.POST.get('email')
            request.user.save()
            request.session['error_message'] += "Addresse email changée.\\n"
            request.session['error_not_seen'] = True
            print('Changement de mail pour ' + request.user.username)
        elif request.POST.get('email') != request.user.email:
            request.session['error_message'] += "Addresse email incorrecte.\\n"
            request.session['error_not_seen'] = True

        form = ConfigColorsForm(request.POST, request.FILES, instance=Joueur.objects.get(
            utilisateur=request.user.id))
        if form.is_valid():
            form.clean()
            # On supprimme le fond decran si upload d'un nouveau ou demande de le supprimmer !!
            try:
                if (not form.cleaned_data['background_file'] or
                        not ('user_' + str(request.user.id) + '/') in str(form.cleaned_data['background_file'])):
                    remove(path.join(settings.MEDIA_ROOT, Joueur.objects.get(
                           utilisateur=request.user.id).background_file.name))
            except Exception as e:
                print("Error : " + str(e))
            form.save()

        return redirect('jeux:config')
    else:
        request.session['error_message'] += "Mot de passe actuel incorrect.\\n"
        request.session['error_not_seen'] = True
        return redirect('jeux:config')


def reset_password(request):
    if request.method == 'POST':
        if request.POST.get('email'):
            print('Email : ' + request.POST.get('email'))
            try:
                user_concerned = User.objects.get(email=request.POST.get('email'))
            except User.DoesNotExist:
                return HttpResponse(200)
        else:
            print('Nom d\'utilisateur : ' + request.POST.get('username'))
            try:
                user_concerned = User.objects.get(username=request.POST.get('username'))
            except User.DoesNotExist:
                return HttpResponse(200)
        print('Utilisateur trouvé.')
        try:

jeux/views/accueil.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from ..models import Player, VideogameRating
from .gestionnaire_erreur import gestionnaire_erreur
from .joueur_options import joueur_colors, joueur_background


@login_required(login_url="/")
@gestionnaire_erreur
def accueil(request, error_message=False):
    try:
        joueur = Player.objects.get(user=request.user.id)
    except Exception:
        request.session["error_message"] += "Utilisateur introuvable.\\n"
        request.session["error_not_seen"] = False
        return redirect("jeux:index")
    else:
        amis = {}
        liste_jeux = {}
        for ami in joueur.friends.exclude(user__groups__name="guest").all():
            amis[ami.user.username] = []
            for jeu in ami.videogames_list.all():
                try:
                    vote = (
                        VideogameRating.objects.filter(joueur_concerne=ami.id)
                        .filter(jeu_concerne=jeu.id)
                        .get()
                        .rating
                    )
                except Exception:
                    vote = 5
                amis[ami.user.username].append([jeu.title, vote])

        for jeu in joueur.videogames_list.all():
            liste_jeux[jeu.title] = {}
            liste_jeux[jeu.title]["id"] = jeu.id
            liste_jeux[jeu.title]["pvp"] = jeu.pvp
            liste_jeux[jeu.title]["coop"] = jeu.coop
            liste_jeux[jeu.title]["f2p"] = jeu.f2p
            liste_jeux[jeu.title]["joueurs_online"] = jeu.max_online_players
            liste_jeux[jeu.title]["joueurs_hot_seat"] = jeu.max_hot_seat_players
            try:
                liste_jeux[jeu.title]["my_vote"] = (
                    VideogameRating.objects.filter(player=joueur.id)
                    .filter(videogame=jeu.id)
                    .get()
                    .rating
                )
            except Exception:
                liste_jeux[jeu.title]["my_vote"] = 5

        if User.objects.get(username=joueur.user).email == "":
            request.session[
                "error_message"
            ] += "Veuillez remplir votre addresse mail dans Mon Compte.\\n"
            request.session["error_not_seen"] = False

        return render(
            request,
            "jeux/accueil.html",
            {
                "amis": amis,
                "liste_jeux": liste_jeux,
                "colors": joueur_colors(request.user.id),
                "background_image": joueur_background(request),
            },
        )

jeux/views/gestionnaire_erreur.py
def gestionnaire_erreur(func):
    """Fonction qui gère les erreurs"""
    def inner(request, *args, **kwargs):
        if 'error_not_seen' in request.session and 'error_message' in request.session:
            if request.session['error_not_seen']:
                request.session['error_not_seen'] = False
            else:
                request.session['error_message'] = ''
        else:
            request.session['error_message'] = ''
            request.session['error_not_seen'] = False
        return func(request, *args, **kwargs)
    return inner

jeux/views/joueur_options.py
from ..models import Player


def joueur_colors(joueur_id):
    """Fonction pour avoir la liste des couleurs de l'utilisateur logé"""
    try:
        joueur = Player.objects.get(user=joueur_id)
    except Exception as e:
        print(e)
    return {
        "body_background": joueur.color_body_background,
        "body_text": joueur.color_body_text,
        "nav_background": joueur.color_nav_background,
        "nav_link_active": joueur.color_nav_link_active,
        "nav_link_hover": joueur.color_nav_link_hover,
        "nav_link": joueur.color_nav_link,
        "nav_text": joueur.color_nav_text,
    }


def joueur_background(request):
    """Fonction pour avoir le fond d'écran de l'utilisateur logé"""
    try:
        background_image = Player.objects.get(user=request.user.id).background_file.url
    except Exception:
        background_image = ""
    return background_image

jeux/views/mes_amis.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .joueur_options import joueur_colors, joueur_background
from .gestionnaire_erreur import gestionnaire_erreur


@login_required(login_url='/')
@gestionnaire_erreur
def mes_amis(request):
    return render(request, 'jeux/mes_amis.html',
                  {'colors': joueur_colors(request.user.id), 'background_image': joueur_background(request)})

jeux/templates/jeux/config.html
{% extends "jeux/core.html" %}
{% load static %}
{% block content %}
<div class="container content_holder">
    <div class="row justify-content">
        <h2>Mon compte :</h2>
    </div>
    <br>
    <form action="{% url 'jeux:change_info' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group form check">
            <div class="form-row">
                <div class="col-sm">
                    <h4>Configuration :</h4>
                    <label for="pseudo">Pseudo :</label>
                    <br>
                    <input type="text" name="pseudo" value="{{ request.user.username }}" required>
                    <br>
                    <label for="mail">Addresse mail :</label>
                    <br>
                    <input type="text" name="email" value="{{ request.user.email }}">
                    <br>
                    <label for="password_new_1" id="password_validator">Nouveau mot de passe : <i class="far fa-question-circle"></i></label>
                    <br>
                    <input type="password" name="password_new_1">
                    <br>
                    <label for="password_new_2">Retapez le mot de passe :</label>
                    <br>
                    <input type="password" name="password_new_2">
                </div>
                <div class="col-sm">
                    <h4>Couleurs :</h4>
                    {% for item in form_colors %}
                        {% if 'color' in item.name %}
                            {{ item }} {{ item.label }}<br>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="col-sm-5">
                    <h4><label for="fond_decran">Fond d'écran :</label></h4>
                    {{ form_colors.background_file }}
                </div>
            </div>
            <br><br><br><br><br><br><br>
            <div class="form-row">
                <div class="col-sm">
                    <label for="password">Mot de passe actuel :</label>
                    <br>
                    <input type="password" name="password" required>
                </div>
                <div class="col-sm">
                    <br>
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="width: 100%;">Envoyer <i class="fas fa-sign-in-alt"></i></button>
                </div>
            </div>
        </div>
    </form>
    {{ password_validator }}
</div>
{% endblock content %}
{% block script %}
<script type="text/javascript">
    $(document).ready(function(){
        if(window.location.pathname === '/config'){
            $("#link-config").addClass('active');
        }
    });
    $('#password_validator').click(() => alert("{{ password_validators }}"));
</script>
{% endblock script %}
{% block style %}
<style type="text/css">
</style>
{% endblock style %}

jeux/templates/jeux/core.html
{% load static %}
<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Required meta tags -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="shortcut icon" href="{% static 'jeux/images/favicon.png' %}">
    <link rel="icon" href="{% static 'jeux/images/favicon.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'jeux/css/index.css' %}">

    <title>{% block title %}LANRumble{% endblock title %}</title>
</head>
<body>
    {% block navbar %}
    <nav class="navbar fixed-top navbar-expand-md">
        <a class="navbar-brand" href="#">
            <object data="{% static 'jeux/images/logo.svg' %}" type="image/svg+xml" id="logo">
                <img src="{% static 'jeux/images/logo.png' %}" />
            </object>
        </a>
        <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarSupportedContent">
            {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" id="link-accueil" href="{% url 'jeux:accueil' %}">Accueil</a>
                <li class="nav-item">
                    <a class="nav-link" id="link-societe" href="{% url 'jeux:jeux_societe' %}">Jeux de Societe</a>
                <li class="nav-item">
                    <a class="nav-link" id="link-config" href="{% url 'jeux:config' %}">Mon Compte</a>
                <li class="nav-item">
                    <a class="nav-link" id="link-amis" href="#">Mes Amis</a>
                    <!-- {% url 'jeux:mes_amis' %} -->
                <li class="nav-item">
                    <a class="nav-link" id="link-jeux" href="{% url 'jeux:mes_jeux' %}">Mes Jeux Vidéos</a>
                </li>
                {% if user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" id="link-jeux" href="{% url 'admin:index' %}">Admin</a>
                </li>
                {% endif %}
            </ul>
            <div class="navbar-text" id="user_name">
                {{ user.username }}&nbsp;&nbsp;
            </div>
            <form class="form-inline my-2 my-lg-0" action="{% url 'jeux:logoutside' %}" method="get">
                <button class="btn btn-outline-danger my-2 my-sm-0" type="submit"><i class="fas fa-sign-out-alt"></i> Logout</button>
            </form>
            {% else %}
            <ul class="navbar-nav mr-auto">
            </ul>
            <form action="{% url 'jeux:loginside' %}" method="post">
                {% csrf_token %}
                <div class="input-group">
                    <div class="col-sm">
                        <input class="form-control mr-sm-2" type="text" id="pseudo" name="pseudo" value="Pseudo :">
                    </div>
                    <div class="col-sm">
                        <input class="form-control mr-sm-2" type="password" id="pass" name="password" value="Mot de passe :">
                    </div>
                    <div class="col-sm">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-sign-in-alt"></i></button>
                        <button class="btn btn-secondary my-2 my-sm-0" id="lost_password" type="button"><i class="fas fa-key"></i></button>
                    </div>
                </div>
            </form>
            {% endif %}
        </div>
    </nav>
    {% endblock navbar %}
    {% block content %}
    {% endblock content %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% if request.session.error_message %}
        <script>
            $(document).ready(() => alert("{% autoescape off %}{{ request.session.error_message }}{% endautoescape %}"));
        </script>
    {% endif %}
    {% block script %}
    {% endblock script %}
    {% block style %}
    {% endblock style %}
    {% block colors %}
    <style type="text/css">
        {% if user.is_authenticated %}
        body{
            color: {{ colors.body_text }};
            background-color: {{ colors.body_background }};
        }
        {% if background_image != "" %}
        body{
            background:linear-gradient(
             rgba({{ colors.body_background|slice:"1:3" }}, {{ colors.body_background|slice:"3:5" }}, {{ colors.body_background|slice:"5:7" }}, 0.8), 
             rgba({{ colors.body_background|slice:"1:3" }}, {{ colors.body_background|slice:"3:5" }}, {{ colors.body_background|slice:"5:7" }}, 0.8)
             ),url("{{ background_image }}");
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center;
            background-size: auto auto;
        }
        {% endif %}
        nav{
            color: {{ colors.nav_text }};
            background-color: {{ colors.nav_background }};
            img{
                height: 32px;
                width: 32px;
            }
        }
        a #logo:hover{
            fill: black;
        }
        nav a{
            color: {{ colors.nav_link }};
        }
        nav a.active{
            color: {{ colors.nav_link_active }};
        }
        nav a:hover{
            color: {{ colors.nav_link_hover }};
        }
        li.nav-item{
            border-color: {{ colors.nav_link }};
        }
        {% else %}
        body{
            color: #fff;
            background-color: #222;
        }
        nav{
            color: #fff;
            background-color: #111;
        }
        nav a{
            color: #900;
        }
        nav a.active{
            color: #f00;
        }
        nav a:hover{
            color: #fff;
        }
        li.nav-item{
            border-color: #300;
        }
        {% endif %}
        tr{
            /*display: inline-block;*/
            white-space: nowrap;
        }
    </style>
    {% endblock colors %}
</body>
</html>

jeux/templates/jeux/mes_amis.html
{% extends "jeux/core.html" %}
{% load static %}
{% block content %}
<div class="container content_holder">
    <div class="row justify-content">
        
    </div>
</div>
{% endblock content %}

jeux/templates/jeux/password_reset.html
{% extends "jeux/core.html" %}
{% load static %}
{% block content %}
<div class="container content_holder">
    <div class="row justify-content-center">
        <div class="col-sm-12">
            <form action="/reset_page" method="post">
                {% csrf_token %}
                <table>
                    <tr><th id="password_validator">{{ form.new_password_1.label }} <i class="far fa-question-circle"></i></th><th>{{ form.new_password_1 }}</th></tr>
                    <tr><th>{{ form.new_password_2.label }}</th><th>{{ form.new_password_2 }}</th></tr>
                    <tr hidden><th><input type="hidden" value="{{ token }}" id="token" name="token"></th><th></th></tr>
                </table>
                <input type="submit" value="Envoyer" class="btn btn-outline-success my-2 my-sm-0">
            </form>
        </div>
    </div>
</div>

{% endblock content %}
{% block script %}
<script>
    $('#password_validator').click(() => alert("{{ password_validators }}"));
</script>
{% endblock script %}
{% block style %}
<style type="text/css">
    table, tr, th {
        border: 0px solid rgba(0,0,0,0);
        text-align: left;
    }
    tr:hover{
        background-color: rgba(255,255,255,.0);
    }
</style>
{% endblock style %}